### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by LJPdream** [wtffly/DroidBinding_AMap#1]
我引进该包到项目，生成时就报错，请问你有没有进一步研究

**Comment by FleetingWang** [comment]
@LJPdream 这个库是帮助其他人绑定的，他后来没有反映包有问题，但我也没具体测试。问下，具体是什么样的错误？

**Comment by LJPdream** [comment]
我这边，vs输出的是中文乱码：

閿欒: AMapNaviListenerImplementor涓嶆槸鎶借薄鐨? 骞朵笖鏈鐩朅MapNaviListener涓殑鎶借薄鏂规硶OnUpdateTrafficFacility(TrafficFacilityInfo)
public class AMapNaviListenerImplementor
娉? obj\Debug\android\src\mono\com\amap\api\maps\AMap_onMapPrintScreenListenerImplementor.java浣跨敤鎴栬鐩栦簡宸茶繃鏃剁殑 API銆?
娉? 鏈夊叧璇︾粏淇℃伅, 璇蜂娇鐢?-Xlint:deprecation 閲嶆柊缂栬瘧銆?
娉? 鏌愪簺杈撳叆鏂囦欢浣跨敤浜嗘湭缁忔鏌ユ垨涓嶅畨鍏ㄧ殑鎿嶄綔銆?
娉? 鏈夊叧璇︾粏淇℃伅, 璇蜂娇鐢?-Xlint:unchecked 閲嶆柊缂栬瘧銆?
1 涓敊璇?

**Comment by LJPdream** [comment]
还有我的开发环境是vs2015，我只是引进而已，还没有其他操作，还有能不能请楼主帮我用新的高德包绑定一个，当然楼主，要是愿意教一下我就不胜感激了，主要是那个metadata这个文件不会用

**Comment by FleetingWang** [comment]
@LJPdream 应该和这个错误信息类似：

> 注: E:\crifan\DevRoot\Osmand-master\OsmAnd-java\src\net\osmand\util\GeoPointParserUtil.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

可以把-Xlint:deprecation 和 -Xlint:unchecked 加到Xamarin的编译选项中，具体位置在：项目属性-Android选项-高级-其他Java选项

我有时间绑定一下新版本

**Comment by LJPdream** [comment]
加了，还是报一样的错误，还有希望楼主绑定好新的库，可以告诉我一声，谢谢了

**Comment by FleetingWang** [comment]
@LJPdream 更新了，有问题记得反馈哈
